#page title
page_title                                : "Reading List iOS app: track and plan books to read"                                        # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1217139955                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
#presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : /assets/AppIcon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Reading List                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Plan the books your want to read. Keep track of what books you've read and when. Motivate yourself to read more.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Andrew Bennet                                
your_link                                 : https://andrewbennet.com                     
#your_city                                 : London                      
email_address                             : feedback@readinglist.app
#facebook_username                         :                                           
#instagram_username                        : ebaehr
twitter_username                          : ReadingListApp
github_username                           : AndrewBennet
#youtube_username                          :
stackoverflow_username                    : 5513562/andrew-bennet


faqs:

  - title: Is it free?
    description: "Yes! Reading List is free to use, has no ads and keeps your data private. If you do want to contribute to the development of the app, you can make a donation via an in-app purchase. This helps contribute to the costs of developing an iOS app (resources, test devices, Apple developer subscription, etc)."

  - title: Can you see my data?
    description: "Nope! Your book data stays on your own device, and in your private iCloud account (if Backup is configured) – user book data is hidden from me and from anyone else. The app is open source, so anyone can <a href='https://github.com/AndrewBennet/ReadingList'>check in the source code</a> if they wish. The app does send crash reports and some anonymous usage statistics – how many times the various features of the app are used – via <a href='https://firebase.google.com/docs/analytics'>Google Firebase Analytics</a>, to help me work out what features to prioritise. If you'd rather not have this information sent, you can opt-out in Settings > General."

  - title: Can I contribute to the app?
    description: "Absolutely! The app is open source, and I'd welcome contributions from anyone familiar with iOS app development in Swift. A few released features have been contributed by other developers. If you have an idea for a feature you'd like to add, feel free to contact me to discuss, or raise an <a href='https://github.com/AndrewBennet/ReadingList/issues'>issue on GitHub</a>."

  - title: How is it different from Goodreads?
    description: "Goodreads is a useful app, but there few negatives when using it as a reading journal:<ul>
    <li>It requires continuous internet connectivity to use. If offline (for example if on a plane or subway), it can't be used.</li>
    <li>The process of logging a book's start or finish date, or moving a book between shelves, takes multiple taps, often with loading screens between each tap.</li>
    <li>There are many more features than the book journal features. This means it can be quite confusing to use.</li>
    </ul>
    Reading List was developed out of a frustration of these kind of issues! The app is fully functional while offline, and has been developed to make the journal interaction aspects as simple and quick as possible.
    "

  - title: Why can't I find the book I'm looking for?
    description: "The online book metadata lookup is provided by Google Books. Google Books does not index every ISBN that exists for a given book, so sometimes the barcode scan functionality will not find the book. In those cases, however, another edition of the book can be found by searching for the ISBN – if this occurs, tap Yes when asked if you wish to perform a more general search.

    If the book cannot be found even when performing a general search, it may be that Google Books does not know about the book. In this case, the book metadata may have to be entered manually into the app."

  - title: Can I record re-reads of a book?
    description: "Unfortunately not – this a current limitation. In future, you will be able to record multiple reading log entries for each book."

  - title: How do I add a Widget to my iPhone homescreen?
    description: "If you are running iOS 14 or later, you can add a widget showing your current or recently finished books to your homescreen. Make sure you have the latest version of Reading List installed, and follow <a href='https://support.apple.com/en-gb/guide/iphone/iphb8f1bf206/ios'>the instructions</a> Apple provides to learn how to do so."

  - title: Is my data safe?
    description: "Reading List automatically backs up your data to iCloud on a daily basis. So if you lose or replace your device, you'll be prompted to restore your data on the new device. The backup frequency can be configured at Settings > Backup & Restore."

#  - title: How Can I Copy My Books From My Previous System?
#    description: "If you've been using some other app or system to catalog your books, you might want to import your historical reading into Reading List. To do this, you'll need to generate a CSV spreadsheet of your book data. "


# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Easily Find Books
    description                           : Add your books by scanning a barcode, or by searching online
    fontawesome_icon_name                 : search

  - title                                 : Full Metadata Control
    description                           : All metadata is fully editable
    fontawesome_icon_name                 : pencil-alt

  - title                                 : Track Your Reading
    description                           : Log start and finish dates for each book
    fontawesome_icon_name                 : calendar-alt

  - title                                 : Take Notes
    description                           : Add star ratings and notes to every book
    fontawesome_icon_name                 : star

  - title                                 : Record Current Position
    description                           : Add your current page or percentage for books currently reading
    fontawesome_icon_name                 : stopwatch

  - title                                 : Import and Export Data
    description                           : Export to, or import from, a simple CSV file
    fontawesome_icon_name                 : file-upload

  - title                                 : Sync via iCloud
    description                           : Sync all data across all your devices via iCloud
    fontawesome_icon_name                 : cloud

  - title                                 : Open Source
    description                           : Free to use and open source
    fontawesome_icon_name                 : smile

# Theme Settings
topbar_color                              : "#ecf0f1"
topbar_transparency                       : 1
topbar_title_color                        : "#000000"

#cover_image                               : https://media.istockphoto.com/photos/bookstore-public-old-library-creativity-concept-picture-id943322510                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#000000"
app_price_color                           : "#000000"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"





####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
